### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by frranck**

### CODE REVIEW

**Comment by ligi** [comment]
Can you squash both commits?

**Comment by frranck** [comment]
@ligi You don't have the option in the squash & merge button ?

**Comment by ligi** [comment]
unfortunately I do not have this button:

selection_024

thanks!

**Comment by ligi** [comment]
@vog can we enable this for this repo?

**Comment by vog** [comment]
I just enabled it. It is under "settings". Now both "Squash+Merge" and "Rebase+Merge" are enabled.

However, "Squash+Merge" just became the default, because it appears further up in the list. I haven't yet figured out how to change that default, I guess this is not possible in GitHub.

**Pull request merged**
