### PR TITLE
Adds all the BHTL 41 projects I could find

### PR DESCRIPTION
**Pull request by Miserlou**

### CODE REVIEW

**Comment by Miserlou** [comment]
My favorite one was the guy who was just `cat`ing image frames to the linux video devices to make the big-red-wall-of-lights show gifs (I think), but I can't find that anywhere, he was just presenting off of his laptop.

**Comment by vog** [comment]
@stefanhoth @ligi Do we have any possibility to find the remaining projects presented at BHNT 41?

**Comment by ligi** [comment]
@johnjohndoe has twittered a lot of them over the time - but I think we might just live with it. I emailed some people I knew might have some info. But at least the future is secure with this repo - should have done so from the beginning ;-)

**Comment by vog** [comment]
Are we at least sure about the ordering? (i.e. that these were the first, second and third presentations)

If not, I propose to use an unordered list instead, for now, until we have more information.

**Comment by stefanhoth** [comment]
👍  for unordered list.

As for the remaining ones I couldn't find the poll in my GDrive so I guess I was not involved with it. Sorry.

**Comment by ligi** [comment]
also :+1: for unsorted list

**Comment by Miserlou** [comment]
Changed to unordered list.

**Comment by vog** [comment]
I'm not a fan of separate fixup commits if we can avoid this, so I squashed both into a single commit to have a cleaner history.

**Comment by johnjohndoe** [comment]
@stefanhoth I did the poll last month using Google Docs. The document is still there. If you used the same you should be able to reincarnate them.

Other then that there should be a couple of project one can find on [Twitter searching for `#bhnt`](https://twitter.com/search?f=tweets&vertical=default&q=%23bhnt&src=typd).

**Comment by johnjohndoe** [comment]
@Miserlou 

> My favorite one was the guy who was just `cat`ing image frames to the linux video devices to make the big-red-wall-of-lights show gifs (I think), but I can't find that anywhere, he was just presenting off of his laptop.

That was @MichaelKreil with the MateLight.

**Comment by vog** [comment]
@johnjohndoe Your comments are very helpful, but somewhat lost in this closed ticket. I created two issues and one pull request out of it:

* #53 Issue: Integrate information from Twitter 
* #54 Issue: Add information from Google Docs polls
* #55 Pull Request: Add Mate Light to BHNT#41

**Pull request merged**
