### PR TITLE
code for presentation

### PR DESCRIPTION
**Pull request by nolash**
Dunno if this is the way you want it, but you'll tell me if not I'm sure :) thanks for letting me show.

### CODE REVIEW

**Comment by ligi** [comment]
I think it would make sense make a separate repo for your code and we then link to it - we usually do not add the code here.

**Comment by nolash** [comment]
ok, someone mentioned a pull request at the show, dunno why. THanks.

**Comment by ligi** [comment]
yes - this was @vog - but he ment PRs with links to code - not PRs with the code ;-)

**Comment by nolash** [comment]
Makes sense, really. So: https://github.com/nolash/ethereum-midi-simulation

**Comment by ligi** [comment]
:+1:  is already listed on - http://berlin.hackandtell.org

**Pull request closed without merging**
